### ISSUE TITLE
High Transaction Fees

### ISSUE THREAD

**Issue by halogen857** [bilix-software/solana-pump-fun#12]
## Issue Description
I've noticed significantly higher transaction fees when using this library for PumpFun purchases compared to using PumpFun's interface directly.

### Using This Library
**Setup:**
```ts
await pumpFunBuy(
execution, privateKey, mintAddress,
0.0001, // amount
0.001, // priority fee
0.02 // slippage
):
```

**Results in Solscan:**
• Base Fee: 0.0014 SOL (~ $0.25)
• Priority Fee: 0.0014 SOL (~ $0.25)
• Total: 0.0028 SOL (~ $0.50)

### Using PumpFun Directly
**Setup:**
• Max Slippage: 2%
• Priority Fee: 0.001 SOL
<img width="264" alt="Screenshot 2024-10-30 at 5 40 04 PM" src="https://github.com/user-attachments/assets/df587483-c2c7-48c7-a221-c25ec2eaabf6">

**Results in Solscan:**
- Base Fee 0.000015 SOL ($0.002610)
- Priority Fee 0.00001 SOL ($0.001731)
- Total: 0.000025 SOL (~ $0.005)
Note: Pumpfun might be dynamic. Even though I set the numbers in the UI, Pumpfun might use the lowest numbers possible for a better deal. Not sure though.

## Summary
The library appears to be charging approximately 100x more in fees compared to direct usage. Is this intended behavior or a potential issue?

Note: The Priority Fee is optional and we can set $0.0 for it. The Base Fee is not optional.

**Comment by dylan-barnes** [comment]
The fee is programmed into the smart contract. It is 1% of transaction fee

**Comment by halogen857** [comment]
@dylan-barnes Please read my example. I paid 0.0001 SOL which is $0.017483 USD. So therefore, 1% of $0.017483 USD is only $0.00017483. 

This library the fees are $0.25 USD and more. 

So there is an issue.

**Comment by bilix-software** [comment]
I will look into it

**Comment by bilix-software** [comment]
To try it I made two transactions on pumpfun. One via the website and one via this package.

Pump.fun interface: [(tx](https://solscan.io/tx/4mYT9pYouyk5oTFopMgm5pSbPW97pCTkimEgSvYe6viRWbHVquNp1uifUyuWey5XSqS12swo9GDEBYk3HMqBuJ52))
Total fee:
0.000418 sol
----------
0.000413 prio fee
0.000005 normal fee

+ 0.003 jito tip

Transaction using this library with 0.001 prio fee setting: [(tx)](https://solscan.io/tx/2D7cw4u2q1yksqMLNRxeAW4NfXtGbZpYSU2HQzZSERvCx2bPpzMQpN8G5zxzQx9V7kfefnGHwaXdWZAwR8XaT22G)

Total fee:
0.001005 
----------
0.001 prio fee
0.000005 normal fee

So as you can see the prio fee is something the user can toggle and will be reflected in the cost of the transaction. But the normal fee of the transaction is the same for both. Pumpfun then also uses a jito tip which might make it faster, but also costs more.
