### ISSUE TITLE
High Transaction Fees (Part 2)

### ISSUE THREAD

**Issue by halogen857** [bilix-software/solana-pump-fun#13]
Follow up to https://github.com/bilix-software/solana-pump-fun/issues/12

Can you show me how you called `pumpFunBuy` function with parameters? 

I called this and got high fees for **Base Fee** and **Prio Fee**. These are two different fees.

This is what I passed for numbers:
```ts
await pumpFunBuy(
execution, privateKey, mintAddress,
0.0001, // amount
0.001, // priority fee
0.02 // slippage
):
```

**Comment by bilix-software** [comment]
` async main() {
        const solIn = 0.1; // Example value, adjust as needed
        const slippageDecimal = 0.25; // Example value, adjust as needed
        const tokenBalance = 1000; // Example value, adjust as needed
        const priorityFeeInSol = 0.001; // Example value for tip to get faster inclusion, adjust as needed

        try {
            // Call the buy function
            await pumpFunBuy(this.transactionMode, this.payerPrivateKey, this.mintAddress, solIn, priorityFeeInSol, slippageDecimal);

            // Call the sell function
            //await pumpFunSell(this.transactionMode, this.payerPrivateKey, this.mintAddress, tokenBalance,priorityFeeInSol, slippageDecimal);
        } catch (error) {
            console.error('Error in main function:', error);
        }
    }`

**Comment by halogen857** [comment]
I think I realize the confusion. It's that Pumpfun has a minimum amount you must buy. I checked Solscan and it doesn't respect really low numbers (that I use for testing). 

Thanks a lot for taking time to help with this. 

And great library!

**Comment by bilix-software** [comment]
No worries, sorry I couldn’t give you a clearer answer
