### ISSUE TITLE
 Program returned error: SBF program panicked

### ISSUE THREAD

**Issue by rzfdsb23** [bilix-software/solana-pump-fun#14]
Hello, can you help me with my problem? Thank you very much
https://solscan.io/tx/qCZYK1ACG6RwLjE9jZZaeDZzuzfnz5SZTgqv34peQevfWo8DMvc3gC7CfqnbkiM7MLxYeXwrATqpL5icvH8TygH

**Comment by bilix-software** [comment]
Hi, can you share your input? It's hard to say just from the tx.

**Comment by rzfdsb23** [comment]
const privateKey = ""; // Replace with your actual private key
const mintAddress = "BjjvKX5k7gQoGRmvQAA5WMr7EkQ2cirGTSGxAznDpump"; //Replace with actual token mint address
const txMode = TransactionMode.Execution; //Set to simulate to test, Execution to perform
const solIn = 0.03; // Example value, adjust as needed
const slippageDecimal = 0.25; // Example value, adjust as needed
const tokenBalance = 10000; // Example value, adjust as needed
const priorityFeeInSol = 0.001; // Example value for tip to get faster inclusion, adjust as needed
await pumpFunBuy(
        this.transactionMode,
        this.payerPrivateKey,
        this.mintAddress,
        solIn,
        priorityFeeInSol,
        slippageDecimal
);
This one?

**Comment by rzfdsb23** [comment]
Could there be something wrong with my json rpc? quicknode

**Comment by rzfdsb23** [comment]
Work out
