### ISSUE TITLE
Simulated selling

### ISSUE THREAD

**Issue by ArbalestAI** [bilix-software/solana-pump-fun#15]
Does the sell side simulation only work if your simulating a real token balance, so simulating after a real buy. I'm trying to create an end-to-end simulated program and I'm stuck as the ATA on the sell side simulation doesn't have a balance as I'm creating it as part of the simulated transaction.

Thanks for any help on this.

**Comment by mikel879881** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WR240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by bilix-software** [comment]
Hi, you either need access to a Jito-Solana RPC so you can simulate a buy + sell bundle. 
https://www.quicknode.com/docs/solana/simulateBundle

Or you could add the buy and sell to a single transaction and natively simulate that through solana web3.

Those are the options as far as I know, but there might be more options available. You would have to modify the code of this library for both options to achieve your end-goal.

**Comment by ArbalestAI** [comment]
Thanks, was afraid of that, because that defeats the purpose of the scalping bot as it needs to wait until it's profitable. I'll keep digging but I think I might not actually be able to simulate a sell side transaction properly.
