### ISSUE TITLE
Sell Doesnt Work

### ISSUE THREAD

**Issue by jl-houss** [bilix-software/solana-pump-fun#8]
Hello, I bought with the pumpFunBuy function 18803 dotfun for 0.0006 sol, and now i'm trying to sell them using the pumpFunSell function, the transaction is confirmed but it doesnt change my dotfun balance

```ts
import CONFIG from "./config";
import { pumpFunBuy, pumpFunSell } from "./lib/pump-fun/swap";
import { TransactionMode } from "./types";

async function main() {
    const transactionMode = TransactionMode.Execution; // Example mode, adjust as needed
    const payerPrivateKey = CONFIG.WALLET_PRIVATE_KEY; // Example key, adjust as needed
    const mintAddress = "7gyaJeFEwLhwvSsGiPjBUDAAyEPypLKeXYyECZSoaT4a"; // Example address, adjust as needed
    const solIn = 0.0006; // Example value, adjust as needed
    const slippageDecimal = 0.15; // Example value, adjust as needed
    const tokenBalance = 18803; // Example value, adjust as needed
    const priorityFeeInSol = 0.00003; // Example value for tip to get faster inclusion, adjust as needed

    try {
        // Call the buy function
        // await pumpFunBuy(transactionMode, payerPrivateKey, mintAddress, solIn, priorityFeeInSol, slippageDecimal);

        // Call the sell function
        await pumpFunSell(transactionMode, payerPrivateKey, mintAddress, tokenBalance, priorityFeeInSol, slippageDecimal);
    } catch (error) {
        console.error('Error in main function:', error);
    }
}

main()
```

`
Transaction confirmed with signature: 4c8r6tPSpB7AAo7NMiG2vDcfmTo36xLtdVAYF98uwE2Zipk4GoKkTJWNsRWaYFkCELheLj8MkGUfdBqw4r17wv5Q

Sell transaction confirmed: 4c8r6tPSpB7AAo7NMiG2vDcfmTo36xLtdVAYF98uwE2Zipk4GoKkTJWNsRWaYFkCELheLj8MkGUfdBqw4r17wv5Q
`

![image](https://github.com/bilix-software/solana-pump-fun/assets/67522466/4c341f2e-66f6-444f-b967-4ab9eedfd7d7)
![image](https://github.com/bilix-software/solana-pump-fun/assets/67522466/7bb0223e-a30b-4d82-9ce3-c829b74eea06)

**Comment by bilix-software** [comment]
Hi, you need to add 6 0's behind the amount you're trying to sell to account for the token decimal offset. It did sell but it sold a tiny amount thats why you don't see your balance change.
See your tx here:
https://solscan.io/tx/4c8r6tPSpB7AAo7NMiG2vDcfmTo36xLtdVAYF98uwE2Zipk4GoKkTJWNsRWaYFkCELheLj8MkGUfdBqw4r17wv5Q

**Comment by jl-houss** [comment]
Oh right, i didnt notice, thanks for your help !

Side question, i'm new with all the solana dev stuff, and i'm missing resources for learning, can you help me with some questions? and if yes, how can i contact you?

**Comment by bilix-software** [comment]
You can contact me at [info@bilix.io](mailto:info@bilix.io)
